##   ____           _                ____
##  / ___|__ _  ___| |_ _   _ ___   / ___|__ _ _ __  _   _  ___  _ __
## | |   / _` |/ __| __| | | / __| | |   / _` | '_ \| | | |/ _ \| '_ \
## | |__| (_| | (__| |_| |_| \__ \ | |__| (_| | | | | |_| | (_) | | | |
##  \____\__,_|\___|\__|\__,_|___/  \____\__,_|_| |_|\__, |\___/|_| |_|
##                                                   |___/
##           ___ ___  _  _ _____ ___ _  _ _   _ ___ ___
##          / __/ _ \| \| |_   _|_ _| \| | | | | __|   \
##         | (_| (_) | .` | | |  | || .` | |_| | _|| |) |
##          \___\___/|_|\_| |_| |___|_|\_|\___/|___|___/
##
## A P-ROC Project by Eric Priepke, Copyright 2012-2013
## Built on the PyProcGame Framework from Adam Preble and Gerry Stellenberg
## Original Cactus Canyon software by Matt Coriale
##

# P-ROC Game Description file for Bally Cactus Canyon
PRGame:
    machineType: wpc95
    numBalls: 4
PRFlippers:
    - flipperLwR
    - flipperLwL
PRBumpers:
    - leftSlingshot
    - rightSlingshot
    - leftJetBumper
    - rightJetBumper
    - bottomJetBumper
PRSwitches:
    # **** Format ****
    # name:
    #   number: <number>
    #   type: <type>
    #
    #   <number> can be: SFx (Flipper switch, labeled Fx in WPC manual
    #                    SDx (Dedicated switch, labeled SDx in WPC manual
    #                    Sx  (Matrix switch, labeled x in WPC manual
    #   <type> can be: 'NO' (normally open.  This is the default; so no need to use this)
    #    'NC' (normally closed.  Common for optos)

    #Flipper Grounded Swithes
    ## EOS switches?
    flipperLwR:
        number: SF2
        label: Right Flipper
        tags: Grounded,0,2
    flipperLwL:
        number: SF4
        label: Left Flipper
        tags: Grounded,0,4

    #Dedicated Grounded Swtches
    leftCoin:
        number: SD1
        label: Left Coin Chute
        tags: Dedicated,0,1
    centerCoin:
        number: SD2
        label: Center Coin Chute
        tags: Dedicated,0,2
    rightCoin:
        number: SD3
        label: Right Coin Chute
        tags: Dedicated,0,3
    fourthCoin:
        number: SD4
        label: 4th Coin Chute
        tags: Dedicated,0,4
    exit: 
        number: SD5
        label: Exit
        tags: Dedicated,0,5
    down: 
        number: SD6
        label: Down
        tags: Dedicated,0,6
    up: 
        number: SD7
        label: Up
        tags: Dedicated,0,7
    enter: 
        number: SD8
        label: Enter
        tags: Dedicated,0,8

    #Regular Switches
    phantomSwitch2:
        number: S11
        label: False Switch 2
        tags: Standard,1,1
    phantomSwitch3:
        number: S12
        label: False Switch 3
        tags: Standard,1,2
    startButton:
        number: S13
        label: Start Button
        tags: Standard,1,3
    plumbBobTilt:
        number: S14
        label: Tilt Plumb Bob
        tags: Standard,1,4
    mineEntrance:
        number: S15
        label: Mine Entrance
        tags: Standard,1,5
    leftOutlane:
        number: S16
        label: Left Outlane
        tags: Standard,1,6
    rightReturnLane:
        number: S17
        label: Right Return Lane
        tags: Standard,1,7
    shooterLane:
        number: S18
        label: Shooter Lane
        tags: Standard,1,8
    tilt:
        number: S21
        label: Slam Tilt
        tags: Standard,2,1
    coinDoorClosed:
        number: S22
        label: Coin Door Closed
        tags: Standard,2,2
    alwaysClosed:
        number: S24
        label: Always Closed
        tags: Standard,2,4
    leftReturnLane:
        number: S26
        label: Left Return Lane
        tags: Standard,2,6
    rightOutlane:
        number: S27
        label: Right Outlane
        tags: Standard,2,7
    bottomRightStandUp:
        number: S28
        label: Bot. Right QD Target
        tags: Standard,2,8
    troughEject:
        number: S31
        label: Trough Eject Sensor
        tags: Standard,3,1
        type: 'NC'
    troughBallOne:
        number: S32
        label: Trough Ball 1
        tags: Standard,3,2
        type: 'NC'
    troughBallTwo:
        number: S33
        label: Trough Ball 2
        tags: Standard,3,3
        type: 'NC'
    troughBallThree:
        number: S34
        label: Trough Ball 3
        tags: Standard,3,4
        type: 'NC'
    troughBallFour:
        number: S35
        label: Trough Ball 4
        tags: Standard,3,5
        type: 'NC'
    leftLoopBottom:
        number: S36
        label: Left Loop Bottom
        tags: Standard,3,6
        type: 'NC'
    rightLoopBottom:
        number: S37
        label: Right Loop Bottom
        tags: Standard,3,7
        type: 'NC'
    minePopper:
        number: S41
        label: Mine Popper
        tags: Standard,4,1
        type: 'NC'
    saloonPopper:
        number: S42
        label: Saloon Popper
        tags: Standard,4,2
        type: 'NC'
    phantomSwitch:
        number: S43
        label: False Switch 1
        tags: Standard,4,3
    topRightStandUp:
        number: S44
        label: Top Right QD Target
        tags: Standard,4,4
    phantomSwitch4:
        number: S45
        label: False Switch 4
        tags: Standard,4,5
    beerMug:
        number: S46
        label: Beer Mug
        tags: Standard,4,6
        debounce: False
    leftBonusLane:
        number: S47
        label: Left Bonus Lane
        tags: Standard,4,7
    jetBumpersExit:
        number: S48
        label: Jet Bumpers Exit
        tags: Standard,4,8
    leftSlingshot:
        number: S51
        label: Left Slingshot
        tags: Standard,5,1
    rightSlingshot:
        number: S52
        label: Right Slingshot
        tags: Standard,5,2
    leftJetBumper:
        number: S53
        label: Left Jet Bumper
        tags: Standard,5,3
    rightJetBumper:
        number: S54
        label: Right Jet Bumper
        tags: Standard,5,4
    bottomJetBumper:
        number: S55
        label: Bottom Jet Bumper
        tags: Standard,5,5
    rightLoopTop:
        number: S56
        label: Right Loop Top
        tags: Standard,5,6
    rightBonusLane:
        number: S57
        label: Right Bonus Lane
        tags: Standard,5,7
    leftLoopTop:
        number: S58
        label: Left Loop Top
        tags: Standard,5,8
    badGuySW0:
        number: S61
        label: Left Drop Target
        tags: Standard,6,1
    badGuySW1:
        number: S62
        label: Left CTR Drop Target
        tags: Standard,6,2
    badGuySW2:
        number: S63
        label: Right CTR Drop Target
        tags: Standard,6,3
    badGuySW3:
        number: S64
        label: Right Drop Target
        tags: Standard,6,4
    rightRampMake:
        number: S65
        label: Right Ramp Make
        tags: Standard,6,5
    rightRampEnter:
        number: S66
        label: Right Ramp Enter
        tags: Standard,6,6
    skillBowl:
        number: S67
        label: Skill Bowl
        tags: Standard,6,7
    rightRampBottom:
        number: S68
        label: Right Ramp Bottom
        tags: Standard,6,8
    trainEncoder:
        number: S71
        label: Train Encoder
        tags: Standard,7,1
    trainHome:
        number: S72
        label: Train Home
        tags: Standard,7,2
    saloonGate:
        number: S73
        label: Saloon Gate
        tags: Standard,7,3
    saloonBart:
        number: S75
        label: Bart Brother Toy
        tags: Standard,7,5
    mineHome:
        number: S77
        label: Mine Home
        tags: Standard,7,7
        type: 'NC'
    mineEncoder:
        number: S78
        label: Mine Encoder
        tags: Standard,7,8
        type: 'NC'
    centerRampEnter:
        number: S82
        label: Center Ramp Enter
        tags: Standard,8,2
    leftRampMake:
        number: S83
        label: Left Ramp Make
        tags: Standard,8,3
    centerRampMake:
        number: S84
        label: Center Ramp Make
        tags: Standard,8,4
    leftRampEnter:
        number: S85
        label: Left Ramp Enter
        tags: Standard,8,5
    topLeftStandUp:
        number: S86
        label: Top Left QD Target
        tags: Standard,8,6
    bottomLeftStandUp:
        number: S87
        label: Bot. Left QD Target
        tags: Standard,8,7
    
PRCoils:
    directDrive0:
        number: 0
        label: Direct Drive 0
        pulseTime: 30
    badGuyDown0:
        number: 1
        label: Bad Guy 0 Down
        pulseTime: 30
        tags: Solenoid
    badGuyDown1:
        number: 2
        label: Bad Guy 1 Down
        pulseTime: 30
        tags: Solenoid
    badGuyDown2:
        number: 3
        label: Bad Guy 2 Down
        pulseTime: 30
        tags: Solenoid
    badGuyDown3:
        number: 4
        label: Bad GUy 3 Down
        pulseTime: 30
        tags: Solenoid
    flipperLwRMain:
        number: FLRM
    flipperLwRHold:
        number: FLRH
    flipperLwLMain:
        number: FLLM
    flipperLwLHold:
        number: FLLH
    moveBart:
        number: FURM
        label: Bart Toy - Move
        tags: Solenoid
    moveBartHat:
        number: FULH
        label: Bart Toy - Hat
        tags: Solenoid
    shakerMotor:
        number: FURH
        lable: Shaker Motor
        tags: Mech
    autoPlunger:
        number: C01
        label: Auto-Plunger
        tags: Solenoid
    badGuyC0:
        number: C02
        label: Left Drop Target
        tags: Mech
    badGuyC1:
        number: C03
        label: Left CTR Drop Target
        tags: Mech
    badGuyC2:
        number: C04
        label: Right CTR Drop Target
        tags: Mech
    badGuyC3:
        number: C05
        label: Right Drop Target
        tags: Mech
    minePopper:
        number: C06
        label: Mine Popper
        tags: Solenoid
    knocker:
        number: C07
        label: Backbox Knocker
        tags: Solenoid
    saloonPopper:
        number: C08
        label: Saloon Popper
        tags: Solenoid
    troughEject:
        number: C09
        label: Trough Eject
        tags: Solenoid
    leftSlingshot:
        number: C10
        label: Left Slingshot
        tags: Solenoid
    rightSlingshot:
        number: C11
        label: Right Slingshot
        tags: Solenoid
    leftJetBumper:
        number: C12
        label: Left Jet Bumper
        tags: Solenoid
    rightJetBumper:
        number: C13
        label: Right Jet Bumper
        tags: Solenoid
    leftGunFightPost:
        number: C14
        label: Left Gunfight Post
        tags: Solenoid
    rightGunFightPost:
        number: C15
        label: Right GUnfight Post
        tags: Solenoid
    bottomJetBumper:
        number: C16
        label: Bottom Jet Bumper
        tags: Solenoid
    mineMotor:
        number: C17
        label: Mine Motor
        tags: Mech
    mineFlasher:
        number: C18
        label: Mine
        tags: Flasher
    leftGunFlasher:
        number: C19
        label: Left Pistol
        tags: Flasher
    rightGunFlasher:
        number: C20
        label: Right Pistol
        tags: Flasher
    leftLoopGate:
        number: C21
        label: Left Loop Gate
        tags: Solenoid
    rightLoopGate:
        number: C22
        label: Right Loop Gate
        tags: Solenoid
    beaconFlasher:
        number: C24
        label: Awards Beacon
        tags: Flasher
    middleRightFlasher:
        number: C25
        label: Right Middle - Red
        tags: Flasher
    saloonFlasher:
        number: C26
        label: Saloon
        tags: Flasher
    backRightFlasher:
        number: C27
        label: Back Right - Red
        tags: Flasher
    backLeftFlasher:
        number: C28
        label: Back Left - Red
        tags: Flasher
    trainReverse:
        number: C37
        label: Train Motor - Reverse
        tags: Mech
    trainForward:
        number: C38
        label: Train Motor - Forward
        tags: Mech

PRLamps:
    rankStranger:
        number: L11
        label: Rank Lamp - Stranger
        tags: Playfield,Main
    rankPartner:
        number: L12
        label: Rank Lamp - Partner
        tags: Playfield,Main
    rankDeputy:
        number: L13
        label: Rank Lamp - Deputy
        tags: Playfield,Main
    rankSheriff:
        number: L14
        label: Rank Lamp - Sheriff
        tags: Playfield,Main
    rankMarshall:
        number: L15
        label: Rank Lamp - Marshall
        tags: Playfield,Main
    starMotherlode:
        number: L16
        label: Badge Point - Motherlode
        tags: Playfield,Badge
    leftBonusLane:
        number: L17
        label: Left Bonus Lane
        tags: Playfield
    rightBonusLane:
        number: L18
        label: Right Bonus Lane
        tags: Playfield
    bountyBeacon:
        number: L21
        label: Beacon - Bounty
        tags: Playfield,Main
    jackpotBeacon:
        number: L22
        label: Beacon - Jackpot
        tags: Playfield,Main
    shootToCollect:
        number: L23
        label: Beacon - Shoot to Collect
        tags: Playfield,Main
    extraBallLitBeacon:
        number: L24
        label: Beacon - Extra Ball
        tags: Playfield,Main
    bountySaloon:
        number: L25
        label: Saloon - Bounty
        tags: Playfield,Main
    saloonArrow:
        number: L26
        label: Saloon - Yellow Triangle
        tags: Playfield,Main
    extraBall:
        number: L27
        label: Mine - Extra Ball
        tags: Playfield,Main
    mineLock:
        number: L28
        label: Mine - Lock
        tags: Playfield,Main
    badGuyL2:
        number: L31
        label: Right Center Drop Target
        tags: Playfield
    badGuyL0:
        number: L32
        label: Left Drop Target
        tags: Playfield
    leftQuickdraw:
        number: L33
        label: Left Quickdraw
        tags: Playfield,Main
    rightRampSoundAlarm:
        number: L34
        label: Right Ramp - Sound Alarm
        tags: Playfield,Main,rightRamp
    rightRampShootOut:
        number: L35
        label: Right Ramp - Shoot-out
        tags: Playfield,Main,rightRamp
    rightRampSavePolly:
        number: L36
        label: Right Ramp - Save Polly
        tags: Playfield,Main,rightRamp
    rightRampJackpot:
        number: L37
        label: Right Ramp - Jackpot
        tags: Playfield,Main,rightRamp
    rightRampCombo:
        number: L38
        label: Right Ramp - Combo
        tags: Playfield,rightRamp
    rightLoopCombo:
        number: L41
        label: Right Loop - Combo
        tags: Playfield,rightLoop
    rightLoopJackpot:
        number: L42
        label: Right Loop - Jackpot
        tags: Playfield,Main,rightLoop
    rightLoopMarksman:
        number: L43
        label: Right Loop - Marksman
        tags: Playfield,Main,rightLoop
    rightLoopGunslinger:
        number: L44
        label: Right Loop - Gunslinger
        tags: Playfield,Main,rightLoop
    rightLoopGoodShot:
        number: L45
        label: Right Loop - Good Shot
        tags: Playfield,Main,rightLoop
    leftReturnQuickdraw:
        number: L46
        label: Left Return Lane QD
        tags: Playfield,Main
    leftGunfightPin:
        number: L47
        label: Left Gunfight
        tags: Playfield,Main
    leftOutGunfight:
        number: L48
        label: Left Outlane - Special
        tags: Playfield,Main
    badGuyL3:
        number: L51
        label: Right Drop Target
        tags: Playfield
    bottomRightQuickdraw:
        number: L52
        label: Bottom Right Quickdraw
        tags: Playfield,Main
    topRightQuickdraw:
        number: L53
        label: Top Right Quickdraw
        tags: Playfield,Main
    centerRampCatchTrain:
        number: L54
        label: Center Ramp - Catch Train
        tags: Playfield,Main,centerRamp
    centerRampStopTrain:
        number: L55
        label: Center Ramp - Stop Train
        tags: Playfield,Main,centerRamp
    centerRampSavePolly:
        number: L56
        label: Center Ramp - Save Polly
        tags: Playfield,Main,centerRamp
    centerRampJackpot:
        number: L57
        label: Center Ramp - Jackpot
        tags: Playfield,Main,centerRamp
    centerRampCombo:
        number: L58
        label: Center Ramp - Combo
        tags: Playfield,centerRamp
    leftRampWhiteWater:
        number: L61
        label: Left Ramp - Whitewater
        tags: Playfield,Main,leftRamp
    leftRampWaterfall:
        number: L62
        label: Left Ramp - Waterfall
        tags: Playfield,Main,leftRamp
    leftRampSavePolly:
        number: L63
        label: Left Ramp - Save Polly
        tags: Playfield,Main,leftRamp
    leftRampJackpot:
        number: L64
        label: Left Ramp - Jackpot
        tags: Playfield,Main,leftRamp
    leftRampCombo:
        number: L65
        label: Left Ramp - Combo
        tags: Playfield,leftRamp
    rightReturnQuickdraw:
        number: L66
        label: Right Return Lane QD
        tags: Playfield,Main
    rightOutSpecial:
        number: L67
        label: Right Outlane Special
        tags: Playfield,Main
    rightGunfightPin:
        number: L68
        label: Right Gunfight
        tags: Playfield,Main
    starStampede:
        number: L71
        label: Badge Point - Stampede
        tags: Playfield,Badge
    starCombo:
        number: L72
        label: Badge Point - Combo
        tags: Playfield,Badge
    starHighNoon:
        number: L73
        label: Badge - High Noon
        tags: Playfield,Badge
    leftLoopCombo:
        number: L74
        label: Left Loop - Combo
        tags: Playfield,leftLoop
    leftLoopJackpot:
        number: L75
        label: Left Loop - Jackpot
        tags: Playfield,Main,leftLoop
    leftLoopRideEm:
        number: L76
        label: Left Loop - Ride em
        tags: Playfield,Main,leftLoop
    leftLoopWildRide:
        number: L77
        label: Left Loop - Wild Ride
        tags: Playfield,Main,leftLoop
    leftLoopBuckNBronco:
        number: L78
        label: Left Loop - Buck N Bronco
        tags: Playfield,Main,leftLoop
    starBartBrothers:
        number: L81
        label: Badge Point - Bart Bros
        tags: Playfield,Badge
    shootAgain:
        number: L82
        label: Shoot Again
        tags: Playfield,Main
    starShowdown:
        number: L83
        label: Badge Point - Showdown
        tags: Playfield,Badge
    badGuyL1:
        number: L84
        label: Left Center Drop Target
        tags: Playfield
    beerMug:
        number: L85
        label: Beer Mug Mod
        tags: Playfield
    beerMugGI:
        number: L86
        label: Beer Mug GI
    jetBumpers:
        number: L87
        label: Jet Bumpers
        tags: Playfield
    startButton:
        number: L88
        label: Start Button
    gi01:
        number: G01
    gi02:
        number: G02
    gi03:
        number: G03
    gi04:
        number: G04
    gi05:
        number: G05

PRBallSave:
    pulseCoils: [minePopper, saloonPopper, leftJetBumper, rightJetBumper, bottomJetBumper,leftSlingshot,rightSlingshot]
    resetSwitches:
        rightOutlane: open
        leftOutlane: open
        rightReturnLane: open
        leftReturnLane: open
        rightRampEnter: open
        leftRampEnter: open
        centerRampEnter: open
        leftLoopBottom: open
        rightLoopBottom: open
        mineEntrance: open
        saloonGate: open
        beerMug: open
        leftJetBumper: open
    stopSwitches:
        shooterLane: closed
        minePopper: active
        saloonPopper: active
        # don't ball search if a flipper button is pressed
        flipperLwL: closed
        flipperLwR: closed

